name: ooda_flutter
repository: https://github.com/neptunestation-com/ooda-flutter

packages:
  - packages/*
  - example

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- dart analyze .
    description: Run static analysis on all packages

  test:
    run: melos exec -- dart test
    description: Run tests in all packages
    packageFilters:
      dirExists: test

  format:
    run: melos exec -- dart format .
    description: Format all packages

  clean:
    run: melos exec -- rm -rf .dart_tool build
    description: Clean build artifacts
